#para compilar este docker se recomomienda etiquetar usuario:nombre
#para ejecutar este docker usar la siguiente secuencia
#docker run -it -p 3000:3000 -v /home/node/app/node_modules -v ~/<rutaProyecto>:/home/node/app usuario:IMAGE_ID

#Volumen para docker-compose
#    volumes:
#      - /home/node/app/node_modules
#      - .:/home/node/app

# #---//// Secuencia para WSL2
FROM node:14.14.0-alpine

#super usuario de la imagen
USER node
 
#se reasgina el directorio con todos los permisos
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
#asignacion de propietario
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
 
CMD ["npm", "run", "start"]

# # #---//// Secuencia solo Linux/Mac
# FROM node:alpine

# WORKDIR '/app'

# COPY ./package.json ./

# RUN npm install

# COPY . .
# CMD ["npm", "run", "start"]